#! /bin/bash
# Licensed under the GNU General Public License Version 2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
####################################################################################################
## Authored by Anthony Nordquist. https://github.com/SalineOS salinelinux@gmail.com 
## Copyright 2013 Anthony Nordquist


tail -f /usr/bin/thunar-view-metadata-script | yad --progress --title=" " --width="325" --window-icon="gtk-info" --image="gtk-info" --text="Reading File Metadata" --pulsate --auto-close  --button="gtk-cancel:9" &

ret="$?"

if [ "$ret" = "252" ]; then
 exit
elif [ "$ret" = "9" ]; then
 exit
fi 

for i in "$@"; do
 CurrentMetaData=$(extract "$i")
 MetaArray=( "${MetaArray[@]}""
""
""$CurrentMetaData" )
done

sleep 3 

ToKill=$(pgrep -f 'tail -f /usr/bin/thunar-view-metadata-script')

kill $ToKill

echo -n "${MetaArray[@]}" | yad --text-info --window-icon="gtk-info" --editable --title="Metadata Reader" --height="800" --width="800" --button=$"gtk-quit:3"

exit